version: "3.9"

services:
  startup_container:
    image: ghcr.io/chidirnweke/secret_santa:latest
    container_name: startup_container
    restart: "no"
    env_file:
      - .env
    command: ["poetry", "run", "alembic", "upgrade", "head"]
    networks:
      - app-network

  secret_santa_backend:
    env_file:
      - .env
    image: ghcr.io/chidirnweke/secret_santa:latest
    container_name: secret_santa_backend
    restart: always
    depends_on:
      - startup_container
    command:
      [
        "poetry",
        "run",
        "fastapi",
        "run",
        "src/secret_santa/app.py",
        "--workers",
        "2",
        "--port",
        "8000",
      ]
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - reverse-proxy
      - telemetry-network

networks:
  reverse-proxy:
    external: true
  telemetry-network:
    external: true
