version: "3.9"

x-shared-environment: &shared-env
  environment:
    INFISICAL_CLIENT_ID: ${INFISICAL_CLIENT_ID}
    INFISICAL_CLIENT_SECRET: ${INFISICAL_CLIENT_SECRET}
    INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
    INFISICAL_ENVIRONMENT: ${INFISICAL_ENVIRONMENT}
    INFISICAL_URL: ${INFISICAL_URL}

services:
  startup_container:
    image: ghcr.io/chidirnweke/secret_santa:latest
    container_name: startup_container

    restart: "no"
    command: ["poetry", "run", "alembic", "upgrade", "head"]
    networks:
      - app_network
    <<: *shared-env

  secret_santa_backend:
    image: ghcr.io/chidirnweke/secret_santa:latest
    container_name: secret_santa_backend
    restart: always
    depends_on:
      - startup_container
    command:
      [
        "poetry",
        "run",
        "fastapi",
        "run",
        "src/secret_santa/app.py",
        "--workers",
        "2",
        "--port",
        "8000",
      ]
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - reverse-proxy
      - telemetry-network
    <<: *shared-env

networks:
  reverse-proxy:
    external: true
  app_network:
    external: true
  telemetry-network:
    external: true
