version: "3.9"

services:
  db:
    image: postgres:16.2-alpine
    restart: always

    ports:
      - "${DB_PORT:-5432}:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: secret_santa

  startup_container:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: "no"
    environment:
      - CONNECTION_STRING=postgresql://admin:admin@db:5432/secret_santa
    depends_on:
      - db
    command: ["poetry", "run", "alembic", "upgrade", "head"]

  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.113.0
    ports:
      - "4317:4317"
    restart: always
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml

  prometheus:
    image: prom/prometheus:v2.55.1
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:3.2.1
    restart: always
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml

  grafana:
    image: grafana/grafana-oss:11.3.0
    restart: always
    ports:
      - "3000:3000"

    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: "http://0.0.0.0:8200"
