"""initial

Revision ID: 07b2b918533c
Revises: 
Create Date: 2024-11-16 03:34:05.172777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b2b918533c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('santa_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buys_for', sa.String(), nullable=False),
    sa.Column('buys_from', sa.String(), nullable=False),
    sa.Column('santa_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['santa_session_id'], ['santa_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_assignments')
    op.drop_table('santa_sessions')
    # ### end Alembic commands ###
