"""Change field names

Revision ID: e8c801d642b5
Revises: 07b2b918533c
Create Date: 2024-12-19 10:07:19.954282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8c801d642b5"
down_revision: Union[str, None] = "07b2b918533c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_assignments", sa.Column("gift_sender", sa.String(), nullable=False)
    )
    op.add_column(
        "user_assignments", sa.Column("gift_receiver", sa.String(), nullable=False)
    )
    op.drop_column("user_assignments", "buys_from")
    op.drop_column("user_assignments", "buys_for")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_assignments",
        sa.Column("buys_for", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_assignments",
        sa.Column("buys_from", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("user_assignments", "gift_receiver")
    op.drop_column("user_assignments", "gift_sender")
    # ### end Alembic commands ###
