"""Added times viewed to table

Revision ID: fe4750e917c0
Revises: e8c801d642b5
Create Date: 2024-12-20 10:41:29.599799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe4750e917c0"
down_revision: Union[str, None] = "e8c801d642b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_assignments", sa.Column("times_viewed", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_assignments", "times_viewed")
    # ### end Alembic commands ###
