name: Build, Push and Deploy frontend

on:
  push:
    branches:
      - main
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v2
      - name: Build static files
        run: cd frontend && npm install && npm run build
      - name: Compress static files
        run: tar -czvf build.tar.gz -C frontend/build/ .

      - name: Secure copy tar file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./build.tar.gz
          target: "~/"

      - name: Extract files on server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/secret_santa/* 
            tar --no-same-permissions --no-overwrite-dir -xzvf ~/build.tar.gz -C /var/www/secret_santa 
            rm ~/build.tar.gz
